# Bibliography data file for wastewater treatment and related systems

[bibliography]

# [bibliography.MoNRCC2040]
# type = "misc"
# author = "E. Ministry of Natural Resources and C. C. of Malaysia"
# title = "The Water Sector Transformation 2040"
# url = "https://sdgs.un.org/partnerships/water-sector-transformation-2040"
# year = "2021"

[bibliography.Kuok2022]
type = "article"
author = "Kuok, K. K. and Chiu, P. C. and Rahman, M. R. and Bakri, M. K. B. and Chin, M. Y."
title = "Effectiveness of Centralized Wastewater Treatment Plant in Removing Emerging Contaminants: A Case Study at Kuching, Malaysia"
journal = "Journal of Water Resource and Protection"
year = "2022"
volume = "14"
number = "9"
pages = "650–663"
doi = "10.4236/jwarp.2022.149034"

[bibliography.Sapkota2025]
type = "article"
author = "Sapkota, B. and Pariatamby, A."
title = "Comprehensive screening and analysis of pharmaceuticals and pharmaceutically active chemicals in wastewater: health and environmental hazards and removal efficiency of wastewater treatment plant in Malaysia"
journal = "Environmental Science and Pollution Research"
year = "2025"
month = "Jan"
volume = "32"
number = "5"
pages = "2577–2591"
doi = "10.1007/s11356-024-35817-y"

[bibliography.Ruzi2023a]
type = "article"
author = "Ruzi, I. I. and Ishak, A. R. and Abdullah, M. A. and Zain, N. N. M. and Tualeka, A. R. and Aziz, M. Y."
title = "Assessment of Heavy Metal Concentrations in Penang, Malaysia’s Wastewater Treatment Plants: A Wastewater-Based Epidemiology Approach"
journal = "Trends in Sciences"
year = "2023"
month = "Feb"
volume = "20"
number = "5"
pages = "6523"
doi = "10.48048/tis.2023.6523"

[bibliography.Ruzi2024]
type = "article"
author = "Ruzi, I. I. et al."
title = "Heavy metal contamination in Sungai Petani, Malaysia: a wastewater-based epidemiology study"
journal = "Journal of Water and Health"
year = "2024"
month = "May"
volume = "22"
number = "6"
pages = "953–966"
doi = "10.2166/wh.2024.241"

[bibliography.Daud2022]
type = "article"
author = "Daud, N. M. and Abdullah, S. R. S. and Hasan, H. A. and Ismail, N. '. and Dhokhikah, Y."
title = "Integrated physical-biological treatment system for batik industry wastewater: A review on process selection"
journal = "Science of The Total Environment"
year = "2022"
month = "May"
volume = "819"
pages = "152931"
doi = "10.1016/j.scitotenv.2022.152931"

[bibliography.Fallahiarezoudar2022]
type = "article"
author = "Fallahiarezoudar, E. and Ahmadipourroudposht, M. and Yakideh, K. and Ngadiman, N. A."
title = "An eco-environmental efficiency analysis of Malaysia sewage treatment plants: an incorporated window-based data envelopment analysis and ordinary least square regression"
journal = "Environmental Science and Pollution Research"
year = "2022"
month = "Jan"
volume = "29"
number = "25"
pages = "38285–38302"
doi = "10.1007/s11356-022-18742-w"

[bibliography.Ishak2022]
type = "article"
author = "Ishak, A. and Mohamad, E. and Hambali, A. and Johari, N. L."
title = "The reliability and process capability assessment of suspended growth sewage treatment plant in Melaka, Malaysia"
journal = "Water Science and Technology"
year = "2022"
month = "Nov"
volume = "86"
number = "9"
pages = "2233–2247"
doi = "10.2166/wst.2022.360"

[bibliography.Ansari2018]
type="article"
author="Ansari, M. and Othman, F. and Abunama, T. and El-Shafie, A."
title="Analysing the accuracy of machine learning techniques to develop an integrated influent time series model: case study of a sewage treatment plant, Malaysia"
journal="Environmental Science and Pollution Research"
year="2018"
month="february"
volume="25"
number="12"
pages="12139--12149-12139--12149"
note="1614-7499"
doi="10.1007/s11356-018-1438-z"

[bibliography.Rahmat2023]
type = "article"
author = "Rahmat, S. and Altowayti, W. A. H. and Othman, N. and Asharuddin, S. M. and Saeed, F. and Basurra, S. and Eisa, T. A. E. and Shahir, S."
title = "Prediction of Wastewater Treatment Plant Performance Using Multivariate Statistical Analysis: A Case Study of a Regional Sewage Treatment Plant in Melaka, Malaysia"
journal = "Water"
year = "2022"
month = "Oct"
volume = "14"
number = "20"
pages = "3297"
doi = "10.3390/w14203297"

[bibliography.Wongburi2023]
type = "article"
author = "Wongburi, P. and Park, J. K."
title = "Prediction of Wastewater Treatment Plant Effluent Water Quality Using Recurrent Neural Network (RNN) Models"
journal = "Water"
year = "2023"
month = "Sept"
volume = "15"
number = "19"
pages = "3325"
doi = "10.3390/w15193325"

[bibliography.Zhang2023a]
type = "article"
author = "Zhang, Y. and Li, C. and Duan, H. and Yan, K. and Wang, J. and Wang, W."
title = "Deep learning based data-driven model for detecting time-delay water quality indicators of wastewater treatment plant influent"
journal = "Chemical Engineering Journal"
year = "2023"
month = "July"
volume = "467"
pages = "143483"
doi = "10.1016/j.cej.2023.143483"

[bibliography.Rahmat2022]
type = "article"
author = "Rahmat, S. et al."
title = "Prediction of Wastewater Treatment Plant Performance Using Multivariate Statistical Analysis: A Case Study of a Regional Sewage Treatment Plant in Melaka, Malaysia"
journal = "Water"
year = "2022"
month = "Oct"
volume = "14"
number = "20"
pages = "3297"
doi = "10.3390/w14203297"

[bibliography.Khalil2023]
type = "article"
author = "Khalil, M. and AlSayed, A. and Liu, Y. and Vanrolleghem, P. A."
title = "Machine learning for modeling N2O emissions from wastewater treatment plants: Aligning model performance, complexity, and interpretability"
journal = "Water Research"
year = "2023"
month = "Oct"
volume = "245"
pages = "120667"
doi = "10.1016/j.watres.2023.120667"

[bibliography.Zhang2025a]
type = "article"
author = "Zhang, Z. et al."
title = "Comprehensive assessment, intelligent prediction, and precise mitigation strategies for greenhouse gas emissions in full-scale wastewater treatment plants"
journal = "Environmental Research"
year = "2025"
month = "Apr"
volume = "270"
pages = "121052"
doi = "10.1016/j.envres.2025.121052"

[bibliography.Peng2025]
type = "article"
author = "Peng, C. and Zhang, S. and Nie, L. and Zang, H."
title = "AI-enhanced multimodal spectroscopy for monitoring volatile organic compounds in pharmaceutical wastewater"
journal = "Water Research"
year = "2025"
month = "Dec"
volume = "287"
pages = "124476"
doi = "10.1016/j.watres.2025.124476"

[bibliography.Shao2024]
type = "article"
author = "Shao, Q. et al."
title = "Low-carbon scheduling of electricity consumption in wastewater treatment plant by using photovoltaic system"
journal = "Science of The Total Environment"
year = "2024"
month = "July"
volume = "933"
pages = "173062"
doi = "10.1016/j.scitotenv.2024.173062"

[bibliography.Colacicco2020]
type = "article"
author = "Colacicco, A. and Zacchei, E."
title = "Optimization of energy consumptions of oxidation tanks in urban wastewater treatment plants with solar photovoltaic systems"
journal = "Journal of Environmental Management"
year = "2020"
month = "Dec"
volume = "276"
pages = "111353"
doi = "10.1016/j.jenvman.2020.111353"

[bibliography.Gomes2023]
type = "article"
author = "Gomes, L. A. and Gonçalves, R. F. and Martins, M. F. and Sogari, C. N."
title = "Assessing the suitability of solar dryers applied to wastewater plants: A review"
journal = "Journal of Environmental Management"
year = "2023"
month = "Jan"
volume = "326"
pages = "116640"
doi = "10.1016/j.jenvman.2022.116640"

[bibliography.Valenzuela2022]
type = "article"
author = "Valenzuela, E. I. and Contreras, J. A. and Quijano, G."
title = "Fast development of microbial cultures for the anaerobic oxidation of CH4 coupled to denitrification employing widely available inocula"
journal = "Biochemical Engineering Journal"
year = "2022"
month = "June"
volume = "184"
pages = "108492"
doi = "10.1016/j.bej.2022.108492"

[bibliography.Seshan2024]
type = "article"
author = "Seshan, S. and Poinapen, J. and Zandvoort, M. H. and van Lier, J. B. and Kapelan, Z."
title = "Limitations of a biokinetic model to predict the seasonal variations of nitrous oxide emissions from a full-scale wastewater treatment plant"
journal = "Science of The Total Environment"
year = "2024"
month = "Mar"
volume = "917"
pages = "170370"
doi = "10.1016/j.scitotenv.2024.170370"

[bibliography.Choi2024]
type = "article"
author = "Choi, P. J. and Lee, J. and Jang, A."
title = "Interconnection between renewable energy technologies and water treatment processes"
journal = "Water Research"
year = "2024"
month = "Sept"
volume = "261"
pages = "122037"
doi = "10.1016/j.watres.2024.122037"

[bibliography.Bertret2025]
type = "article"
author = "Bertret, V. and Latimier, R. L. G. and Monbet, V."
title = "Data assimilation for prediction of ammonium in wastewater treatment plant: From physical to data driven models"
journal = "Water Research"
year = "2025"
month = "Aug"
volume = "282"
pages = "123673"
doi = "10.1016/j.watres.2025.123673"

[bibliography.Junaidi2025]
type = "article"
author = "Junaidi, M. U. M. et al."
title = "The Potential of Zero Liquid Discharge for Sustainable Palm Oil Mill Effluent Management in Malaysia: A Techno-Economic and ESG Perspective"
journal = "Sustainability"
year = "2025"
month = "Nov"
volume = "17"
number = "23"
pages = "10665"
doi = "10.3390/su172310665"

[bibliography.Bey2021]
type = "article"
author = "Bey, M. and Hamidat, A. and Nacer, T."
title = "Eco-energetic feasibility study of using grid-connected photovoltaic system in wastewater treatment plant"
journal = "Energy"
year = "2021"
month = "Feb"
volume = "216"
pages = "119217"
doi = "10.1016/j.energy.2020.119217"

[bibliography.Alali2023]
type = "article"
author = "Alali, Y. and Harrou, F. and Sun, Y."
title = "Unlocking the Potential of Wastewater Treatment: Machine Learning Based Energy Consumption Prediction"
journal = "Water"
year = "2023"
month = "June"
volume = "15"
number = "13"
pages = "2349"
doi = "10.3390/w15132349"

[bibliography.Afan2024]
type = "article"
author = "Afan, H. A. et al."
title = "Data-driven water quality prediction for wastewater treatment plants"
journal = "Heliyon"
year = "2024"
month = "Sept"
volume = "10"
number = "18"
pages = "e36940"
doi = "10.1016/j.heliyon.2024.e36940"

[bibliography.Gandiglio2017]
type = "article"
author = "Gandiglio, Marta and Lanzini, Andrea and Soto, Alicia and Leone, Pierluigi and Santarelli, Massimo"
title = "Enhancing the Energy Efficiency of Wastewater Treatment Plants through Co-digestion and Fuel Cell Systems"
journal = "Frontiers in Environmental Science"
volume = "5"
year = "2017"
url = "https://www.frontiersin.org/journals/environmental-science/articles/10.3389/fenvs.2017.00070"
doi = "10.3389/fenvs.2017.00070"
issn = "2296-665X"

[bibliography.Tsalas2024]
type = "article"
author = "Tsalas, Nikolaos and Golfinopoulos, Spyridon K. and Samios, Stylianos and Katsouras, Georgios and Peroulis, Konstantinos"
title = "Optimization of Energy Consumption in a Wastewater Treatment Plant: An Overview"
journal = "Energies"
volume = "17"
year = "2024"
number = "12"
article_number = "2808"
url = "https://www.mdpi.com/1996-1073/17/12/2808"
issn = "1996-1073"
doi = "10.3390/en17122808"


[bibliography.Sembuil2022]
type = "article"
author = "Sembuil, Azila and Nor, Aznah and A-Halim, Md. Hakim"
title = "Sustainable indicators for designing the wastewater treatment plant"
journal = "IOP Conference Series: Earth and Environmental Science"
year = "2022"
month = "Nov"
publisher = "IOP Publishing"
volume = "1091"
number = "1"
pages = "012057"
doi = "10.1088/1755-1315/1091/1/012057"
url = "https://doi.org/10.1088/1755-1315/1091/1/012057"

[bibliography.Milani2024]
type = "article"
title = "Biogas and photovoltaic solar energy as renewable energy in wastewater treatment plants: A focus on energy recovery and greenhouse gas emission mitigation"
journal = "Water Science and Engineering"
volume = "17"
number = "3"
pages = "283-291"
year = "2024"
issn = "1674-2370"
doi = "10.1016/j.wse.2023.11.003"
url = "https://www.sciencedirect.com/science/article/pii/S167423702300114X"
author = "Sevda Jalali Milani and Gholamreza Nabi Bidhendi"
keywords = "Biogas, Climate change, Photovoltaic cell, Photovoltaic system, Energy recovery, Greenhouse gas reduction"


[bibliography.Zamfir2025]
type = "article"
author = "Zamfir, Florin-Stefan and Carbureanu, Madalina and Mihalache, Sanda Florentina"
title = "Application of Machine Learning Models in Optimizing Wastewater Treatment Processes: A Review"
journal = "Applied Sciences"
volume = "15"
year = "2025"
number = "15"
article_number = "8360"
url = "https://www.mdpi.com/2076-3417/15/15/8360"
issn = "2076-3417"
doi = "10.3390/app15158360"



