[[collection]]
type = "card_simple"
title = "Talentbank Boardroom Challenge 2025"
content = "Future Founder Award, Top 15 Finalist"
date = "Nov 2025"
featured = false
link = "https://media.licdn.com/dms/image/v2/D562DAQHmw66UAwO0Ng/profile-treasury-image-shrink_8192_8192/B56ZpjPlRmIsAk-/0/1762601621388?e=1763208000&v=beta&t=sogyJMagmuucwgFGC5CxqUH2Fl7avESKPiCAmgfq9RU"

[[collection]]
type = "card_simple"
title = "CodeNection Hackathon 2025"
content = "Mentor"
date = "Oct 2025"
featured = false

[[collection]]
type = "card_simple"
title = "4th International Process Control Competition"
content = "Best Visualisation Award"
date = "Aug 2025"
featured = false
link = "https://www.facebook.com/cheme.utp/posts/-empowering-future-engineers-ipcc-2025-ignites-innovation-at-utp-from-22nd-to-24/1178536717631535/"

[[collection]]
type = "card_simple"
title = "PayHack 2025"
content = "Consolation Prize"
date = "Aug 2025"
featured = false

[[collection]]
type = "card_simple"
title = "Alibaba Cloud AI Hackathon 2025"
content = "Top 13 Finalist"
date = "May 2025"
featured = false

[[collection]]
type = "card_simple"
title = "Hack The Future"
content = "Best Presenter"
date = "May 2025"
featured = false
link = "https://media.licdn.com/dms/image/v2/D562DAQEDMuuHmys32Q/profile-treasury-image-shrink_800_800/B56ZiIhQb5HMAY-/0/1754637076660?e=1761206400&v=beta&t=fPyBNLVXhE6CV6PYdPymJyUa4kusdGY04ycv_V_EClg"

[[collection]]
type = "card_simple"
title = "JomHack Varsity Challenge 2025"
content = "Participant"
date = "Apr 2025"
featured = false
link = "https://media.licdn.com/dms/image/v2/D562DAQGRCwgILhsUYg/profile-treasury-image-shrink_1280_1280/B56ZiIigUUHMAQ-/0/1754637404241?e=1761206400&v=beta&t=UUv1poZp-TW-2muHALKdeNRLGzIiZaTAtWYpcy88nvQ"

[[collection]]
type = "card_simple"
title = "Universiti Malaya Hackathon 2025"
content = "4th runner-up"
date = "Apr 2025"
featured = false
link = "https://media.licdn.com/dms/image/v2/D562DAQG_clZwMKaKjw/profile-treasury-image-shrink_8192_8192/B56ZiIhvE2HUAg-/0/1754637202150?e=1761206400&v=beta&t=yZsRKpKhCHUyMsZhRwSOyPN-S1XAaWjrnS0XvKuQhBU"

[[collection]]
type = "card_simple"
title = "20th LIAM Structured Workshop"
content = "Best Presenter Award, Best Team Award"
date = "Dec 2024"
featured = false
link = "https://www.linkedin.com/posts/jienweng_liam-teamwork-insurance-activity-7278028877585596417-49cL?utm_source=share&utm_medium=member_desktop&rcm=ACoAAC1KSdABKaQaEc_UGd2-SprYqjndzpet37I"

[[collection]]
type = "card_simple"
title = "PayHack 2024"
content = "Semi-finalist"
date = "Dec 2024"
featured = false
link = "https://media.licdn.com/dms/image/v2/D562DAQH9Bp2LzIRKKg/profile-treasury-image-shrink_1280_1280/B56ZiIiInzHkAQ-/0/1754637307045?e=1761206400&v=beta&t=aSA6c6nUu-8ECQyHlhd9R8nvjAnsrV1uN1YJdoDLncA"

[[collection]]
type = "card_simple"
title = "Data Science Digital Race 2024"
content = "Finalist"
date = "Oct 2024"
featured = false
link = "https://media.licdn.com/dms/image/v2/D562DAQEjVWe5HWfnYA/profile-treasury-image-shrink_800_800/B56ZiIjDh1H0AY-/0/1754637548439?e=1761206400&v=beta&t=WOm2Yph6VzDSJknVItOLAo9DiqPaXKLejK2N9ggaBTA"
